spring.application.name=scm2.0
server.port=8080


#mysql database configuration
#data source url
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=root

#jpa configuration
#see query in consol
spring.jpa.show-sql=true
#for creating tables and schema automatic
spring.jpa.hibernate.ddl-auto=update
#specific database query understand the dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySql5Dialect

#spring security config

#spring.security.user.name=sudhansu
#spring.security.user.password=sudhansu


#oauth2 client configuration
#config google
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=92602050522-qa1u2pnn7bt2tdj3pd61m3h8o4oip5h6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

#config github

spring.security.oauth2.client.registration.github.client-id=Iv23liaQUWIC5YThGYD9
spring.security.oauth2.client.registration.github.client-secret=eced90cc5ec904157741451d2c1f6116c4a57e8c
spring.security.oauth2.client.registration.github.scope=email,profile


#cloudinary config

cloudinary.cloud.name=dcjw1naqu
cloudinary.api.key=898582845542925
cloudinary.api.secret=p_-USgKNwHTdUjoJnJYxwqDM_sM


#Email Configuration

spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=de445911638240a8f467f52df6db3fd7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.domain_name=scm@demomailtrap.com

#spring boot email starter


#javaMailSender